version: '3.1'

services:

    db:
        image: mariadb:latest
        environment:
            MARIADB_ROOT_PASSWORD: example
            MARIADB_USER: PurBeurre
            MARIADB_PASSWORD: PurBeurre
            MARIADB_DATABASE: PurBeurre
        ports:
            - 3306:3306
            

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
