-- MySQL Script generated by MySQL Workbench
-- Wed Feb 12 10:33:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `mydb`.`foods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`foods` ;

CREATE TABLE IF NOT EXISTS `mydb`.`foods` (
  `food_id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `food_name` VARCHAR(1000) NOT NULL,
  `ingredients` VARCHAR(1000) NULL,
  `additives` VARCHAR(1000) NULL,
  `nutriscore` CHAR(10) NOT NULL,
  `nutrient` VARCHAR(1000) NULL,
  `label` VARCHAR(1000) NULL,
  `store` VARCHAR(1000) NULL,
  `barcode` BIGINT NULL,
  PRIMARY KEY (`food_id`),
  UNIQUE INDEX `food_id_UNIQUE` (`food_id` ASC) VISIBLE,
  CONSTRAINT `category_id`
    FOREIGN KEY (category_id)
    REFERENCES `mydb`.`categories` (category_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`substitutes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`substitutes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`substitutes` (
  `substitute_id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `food_name` VARCHAR(1000) NOT NULL,
  `ingredients` VARCHAR(1000) NULL,
  `additives` VARCHAR(1000) NULL,
  `nutriscore` CHAR(10) NOT NULL,
  `nutrient` VARCHAR(1000) NULL,
  `label` VARCHAR(1000) NULL,
  `store` VARCHAR(1000) NULL,
  `barcode` BIGINT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`substitute_id`),
  UNIQUE INDEX () VISIBLE,
  CONSTRAINT `category_id`
    FOREIGN KEY (category_id)
    REFERENCES `mydb`.`categories` (category_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
