-- MySQL Script generated by MySQL Workbench
-- Wed Feb 26 04:50:39 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `mydb`.`favourites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`favourites` ;

CREATE TABLE IF NOT EXISTS `mydb`.`favourites` (
  `favorite_id` INT NOT NULL AUTO_INCREMENT,
  `food_id` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`favorite_id`),
  CONSTRAINT `fk_food_int`
    FOREIGN KEY (`food_id`)
    REFERENCES `mydb`.`foods` (`food_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_food_int_idx` ON `mydb`.`favourites` (`food_id` ASC) INVISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`foods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`foods` ;

CREATE TABLE IF NOT EXISTS `mydb`.`foods` (
  `food_id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `food_name` VARCHAR(1000) NOT NULL,
  `ingredients` VARCHAR(1000) NULL,
  `additives` VARCHAR(1000) NULL,
  `nutriscore` CHAR(10) NOT NULL,
  `nutrient` VARCHAR(1000) NULL,
  `label` VARCHAR(1000) NULL,
  `store` VARCHAR(1000) NULL,
  `barcode` BIGINT NULL,
  `URL` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`food_id`),
  CONSTRAINT `category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`categories` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `food_id_UNIQUE` ON `mydb`.`foods` (`food_id` ASC) VISIBLE;

CREATE INDEX `category_id_idx` ON `mydb`.`foods` (`category_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
