-- MySQL Script generated by MySQL Workbench
-- Wed Feb 26 04:50:39 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PurBeurre
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PurBeurre` ;

-- -----------------------------------------------------
-- Schema PurBeurre
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PurBeurre` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema PurBeurre
-- -----------------------------------------------------
USE `PurBeurre` ;

-- -----------------------------------------------------
-- Table `PurBeurre`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PurBeurre`.`categories` ;

CREATE TABLE IF NOT EXISTS `PurBeurre`.`categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `PurBeurre`.`favourites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PurBeurre`.`favourites` ;

CREATE TABLE IF NOT EXISTS `PurBeurre`.`favourites` (
  `favorite_id` INT NOT NULL AUTO_INCREMENT,
  `food_id` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`favorite_id`),
  CONSTRAINT `fk_food_int`
    FOREIGN KEY (`food_id`)
    REFERENCES `PurBeurre`.`foods` (`food_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `PurBeurre`.`foods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PurBeurre`.`foods` ;

CREATE TABLE IF NOT EXISTS `PurBeurre`.`foods` (
  `food_id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `food_name` VARCHAR(1000) NOT NULL,
  `ingredients` VARCHAR(1000) NULL,
  `additives` VARCHAR(1000) NULL,
  `nutriscore` CHAR(10) NOT NULL,
  `nutrient` VARCHAR(1000) NULL,
  `label` VARCHAR(1000) NULL,
  `store` VARCHAR(1000) NULL,
  `barcode` BIGINT NULL,
  `URL` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`food_id`),
  CONSTRAINT `category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `PurBeurre`.`categories` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
